#!/usr/bin/bash -eu

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

read -s -p "Password: " password
echo

key=$("${SCRIPT_DIR}"/stretch.py "${password}")

zbarimg --quiet --raw secret.png | base64 -d | gpg -q -d --batch --passphrase "${key}" | xargs --null echo
